apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: asala@emarketingeye.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
       name: sinethra.kube.eme-devops.com
    solvers:
    - http01:
        ingress:
          class: nginx
