apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: sinethra.kube.eme-devops.com
spec:
  secretName: ca-key-pair
  dnsNames:
  - sinethra.kube.eme-devops.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
