apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: "kube-pv"      
