#Create Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wordpress-eme
  name: wordpress-eme
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress-eme
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress-eme
    spec:
      volumes:
      - name: wp-eme-storage
        persistentVolumeClaim:
            claimName: kube-pvc 
      containers:
      - image: wordpress
        name: wordpress
        volumeMounts:
            - name: wp-eme-storage
              subPath: wordpress-eme
              mountPath: /var/www/html
        resources: {}
status: {}
---
#Create NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: wp-eme-service-np
spec:
  type: NodePort
  selector:
    app: wordpress-eme
  ports:
    - port: 80
      targetPort: 80
      #nodePort: 30007
