apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  creationTimestamp: null
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: sinethraks@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
status: {}
