apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  creationTimestamp: null
  name: letsencrypt-production
spec:
  acme:
    email: sinethra@emarketingeye.com
    privateKeySecretRef:
      name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
status: {}
