apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-clusterissuer-production
spec:
  acme:
    email: sinethra@emarketingeye.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-clusterissuer-production
    solvers:
    - http01:
        ingress:
          class: nginx
