apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wildcard-certificate
spec:
  commonName: "sinethra.kube.eme-devops.com"
  dnsNames:
  - sinethra.kube.eme-devops.com
 #- "*.kube.eme-devops.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-clusterissuer-production
  secretName: wildcard-domain-com-tls
