apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        keepalive_timeout  65;
        client_max_body_size 50M;

        proxy_connect_timeout       600s;
        proxy_send_timeout          600;
        proxy_read_timeout          600s;
        send_timeout                600s;

            upstream mysite1 {
                   ip_hash;
                    server 10.104.51.250:80;
            }
            upstream mysite2 {
                   ip_hash;
                    server 10.110.141.227:80;
            }

        include /etc/nginx/conf.d/*.conf;
    }
  mysite1.conf: |
    server{
        listen 80;
        server_name mysite1;
    
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    
        location / {
            proxy_pass http://mysite1;
        }
    }
  mysite2.conf: |
    server{
        listen 80;
        server_name mysite2;
    
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    
        location / {
            proxy_pass http://mysite2;
        }
    }
