#Create Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-lb
  name: nginx-lb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-lb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-lb
    spec:
      volumes:
      - name: nginx-config
        configMap:
                name: nginx-config  
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
            - name: nginx-config
              subPath: nginx.conf
              mountPath: /etc/nginx/nginx.conf
            - name: nginx-config
              subPath: mysite1.conf
              mountPath: /etc/nginx/conf.d/mysite1.conf
            - name: nginx-config
              subPath: mysite2.conf
              mountPath: /etc/nginx/conf.d/mysite2.conf        
        resources: {}
status: {}
---
#Create NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: nginxlb-service-np
spec:
  type: NodePort
  selector:
    app: mysite1
  ports:
    - port: 80
      targetPort: 80
      #nodePort: 80
