apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysite2
  name: mysite2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mysite2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysite2
    spec:
      volumes:
      - name: mysite2-storage
        persistentVolumeClaim:
            claimName: kube-pvc
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
            - name: mysite2-storage
              subPath: nginx/app2
              mountPath: /usr/share/nginx/html
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysite2-service
spec:
  selector:
    app: mysite2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysite2-service-np
spec:
  type: NodePort
  selector:
    app: mysite2
  ports:
    - port: 8080
      targetPort: 80
      #nodePort: 30007
